In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [13]:
n = np.zeros((4,4))
import sys

sys.getsizeof(n)

n.itemsize

8

In [15]:
np.linspace(10,49,dtype = int,num = 40)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
a = np.array([
    [1,2,3],
    [3,4,5]
])

a = np.flip(a,axis=0)

In [19]:
np.flip(a,axis=1)

array([[5, 4, 3],
       [3, 2, 1]])

In [26]:
a.max()

5

In [37]:
n = np.array([1,2,3,4,5,6,7,8,9,10])

In [41]:
n[:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
e = np.linspace(1,16,num=16,dtype=int).reshape(4,4)

In [50]:
e[:,0] = np.zeros(4)

In [53]:
e[:,3] = np.zeros(4)

In [58]:
e[0] = np.zeros(4)

In [59]:
e[3] = np.zeros(4)

In [60]:
e

array([[ 0,  0,  0,  0],
       [ 0,  6,  7,  0],
       [ 0, 10, 11,  0],
       [ 0,  0,  0,  0]])

In [61]:
3 * 0.1

0.30000000000000004

In [63]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [67]:
np.diagflat([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [101]:
mat = np.zeros((4,4),dtype = int)

In [102]:
mat[0::2,::2] = 1
mat[1::2,1::2] = 1

In [103]:
mat

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [7]:
np.tile([1,0],4)
np.tile([0,1],4)

a = np.concatenate((np.tile([1,0],4),np.tile([0,1],4)))

In [20]:
np.tile(a,4).reshape(8,8)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [22]:
np.arange(2*2*4).reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
new = np.arange(11)

In [25]:
a = [new>3,new<8]

In [26]:
a

[array([False, False, False, False,  True,  True,  True,  True,  True,
         True,  True]),
 array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        False, False])]

In [27]:
b = [new,-new]

In [28]:
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])]

In [29]:
np.select(a,b)

array([ 0, -1, -2, -3,  4,  5,  6,  7,  8,  9, 10])

In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,2,3,4],
    [5,6,6,7],
])

b = np.array([
    [1,2,3,4],
    [9,8,7,0],
])

In [3]:
np.intersect1d(a,b)

array([1, 2, 3, 4, 7])

In [12]:
np.timedelta64(1,"D")

numpy.timedelta64(1,'D')

In [2]:
import numpy as np

In [6]:
print(np.datetime64("today","D") - np.timedelta64(1,"D"))
print(np.datetime64("today"))
print(np.datetime64("today","D") + np.timedelta64(1,"D"))

2023-11-11
2023-11-12
2023-11-13


In [9]:
np.timedelta64(1,"D") + np.timedelta64(1,"D")

numpy.timedelta64(2,'D')