In [1]:
wieghts=[0.1,0.2,0.3]
kato=[76,45,44]

def crop_yield(regin,weights):
    result=0
    for x,w in list(zip(regin,weights)):
        result+=x*w
    print(result)

In [2]:
crop_yield(kato,wieghts)

29.8


In [3]:
print(zip(kato,wieghts))

In [4]:
print(list(zip(kato,wieghts)))

[(76, 0.1), (45, 0.2), (44, 0.3)]


In [5]:
int(dict(zip(kato,wieghts)))

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'dict'

In [ ]:
int(str(zip(kato,wieghts)))

In [ ]:
import numpy as np

In [ ]:
numbers=np.array(1,2,3)
numbers

In [ ]:
numbers=[1,2,3,4]
numpy_array=np.array(numbers)

In [ ]:
print(numpy_array)

In [ ]:
numpy_array[0]

In [ ]:
n1=np.array([1,2,3,4])

In [ ]:
print(n1)

In [ ]:
n2=np.array([7,8,9,5])

In [ ]:
print(n2)

In [ ]:
np.dot(n1,n2) # --> dot product of 2 numpy array.

In [ ]:
n1*n2 # --> dot product of n1 and n2

In [ ]:
type(n1)

In [ ]:
np.dot(n1,n2)

In [ ]:
n1.sum()

In [ ]:
(n1*n2).sum()

In [ ]:
np.dot(n1,n2)

In [ ]:
%%time 
# ---> to evaluate the execution time of the code snippet.
np.dot(n1,n2)

In [ ]:
range(1,2)

In [ ]:
list(range(1,2))

In [ ]:
n1.shape()

In [ ]:
n1.shape


In [ ]:
two_d_array=np.array([
    [1,2,3,4],
    [2,3,4,5]
])

In [ ]:
two_d_array

In [ ]:
two_d_array.shape


In [ ]:
lis_t=[1,"bool",True]

In [ ]:
lis_t

In [ ]:
arr=np.array(lis_t)

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr1.dtype

In [ ]:
np.array([1,2.2,2]).dtype

In [ ]:
weights=np.array([
    [1],
    [2],
    [3],
    [4]
])

In [ ]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]
                        ]);
# climate_data a (5,3) matrix.

In [ ]:
weigths=[0.3, 0.2, 0.5]  # ---> a matrix with 3 rows and 1 column. meaning (3,1) matrix.

weight=np.array(weigths)

In [ ]:
np.matmul(climate_data,wieghts)

In [ ]:
np.matmul(climate_data,weight)

In [ ]:
np.matmul(climate_data,wieghts)


In [ ]:
climate_data@weight

In [ ]:
import urllib.request

urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate_text.txt')

In [ ]:
climate_data=np.genfromtxt("climate_text.txt",delimiter=",",skip_header=1)

In [ ]:
climate_data

In [ ]:
climate_data.shape


In [ ]:
climate_data.sum()

In [ ]:
climate_data.dtype


In [ ]:
weights

In [ ]:
wieghts

In [ ]:
weight

In [ ]:
yields=climate_data@weight

In [ ]:
yields.shape


In [ ]:
climate_results=np.concatenate((climate_data,yields.reshape(10000,1)),axis=1)

In [ ]:
climate_results

In [ ]:
arr4=[
    [
        [1,2,3],
        [3,4,5],
    ],
    [
        [2,3,4],
        [5,6,7],
    ]
]

In [ ]:
arr4

In [ ]:
array=np.array(arr4)


In [ ]:
array.shape


In [ ]:
mul=array@weight

In [ ]:
mul.shape

In [ ]:
mul.size

In [ ]:
np.savetxt('climate_results.txt',
           climate_results,
           fmt="%.2f",
           delimiter=",",
           header="temperature,rainfall,humidity,yield_apples",
           comments=""
          )

In [ ]:
result=climate_data+1 #---> here 1 is a scalar as we are adding it in the numpy array. 
#                           1 is going to be added in every element of the climate_data array
result

In [ ]:
arr1=[[1,2,3],
      [2,3,5]]

In [ ]:
arr2=[[1,2,3,4],
      [2,3,5,3]
     ]

In [ ]:
arr=np.array(arr1)
arr_sub=np.array(arr2)

In [ ]:
arr_sub-arr

In [ ]:
arr3=np.array([[1,2,3,],
      [2,3,5,]
     ])

In [ ]:
arr1/arr3

In [ ]:
# arrray broadcasting

arr4=np.array([
    [1,2,3],
])

In [ ]:
arr1/arr4

In [ ]:
arr1 == arr2

In [ ]:
arr2=np.array([[1,2,4]])

In [ ]:
arr1 == arr2

In [ ]:
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
arr1=np.array([
    [1,2,3],
    [5,6,7]
])

In [ ]:
arr==arr1

In [ ]:
arr2=np.array([
    [1,2,3]
])

In [ ]:
arr==arr2

In [ ]:
arr>arr2

In [ ]:
arr!=arr2

In [ ]:
(arr==arr2).sum()

In [ ]:
arr3 = np.array([
    [
        [11, 12, 13, 14], 
        [13, 14, 15, 19]
    ], 
    [
        [15, 16, 17, 21], 
        [63, 92, 36, 18]
    ], 
    [
        [98, 32, 81, 23],      
        [17, 18, 19.5, 43]
    ]
])

In [ ]:
arr3.shape

In [ ]:
arr3.ndim


In [ ]:
arr3[0,0,3]

In [ ]:
arr3

In [ ]:
l=[1,2,3,4]

In [ ]:
l[1:-2]

In [ ]:
np.zeroes((3,2))

In [ ]:
np.zeros((3,4))

In [ ]:
np.zeros((2,2,3))

In [ ]:
np.ones((1,2))

In [ ]:
np.eye((2,5,5))

In [ ]:
np.eye(3)

In [ ]:
np.eye(4,3)

In [ ]:
np.eye(3,4,5)

In [ ]:
np.eye(2,2)

In [ ]:
np.eye(M=2)

In [ ]:
np.eye(N=2)

In [ ]:
help(np.random.rand)

In [ ]:
arr=np.array(np.random.rand(5))

In [ ]:
arr

In [ ]:
np.random.rand(3,4)

In [ ]:
np.random.randn(3)

In [ ]:
np.random.randn(2,3)

In [ ]:
np.full([2,2,3],1)

In [ ]:
np.arange(1,10,2)

In [ ]:
np.arange(20)

In [ ]:
np.linspace(21,199,20)

In [ ]:
np.linspace(10,100,retstep=False)

In [ ]:
import numpy as np

In [ ]:
np.linspace(10,100,retstep=True)

In [ ]:
array,step=np.linspace([1,2,3],[[2,5,6],
                    [4,9,7]],10,retstep=True,axis=0)

In [ ]:
array

In [ ]:
step

In [ ]:
np.mean([1,2,3])

In [ ]:
np.mean([
    [1,2,3],
    [3,5,6]
],axis=(0,1),out=array)

In [ ]:
np.mean(4)

In [ ]:
np.mean([1,2,3],dtype=int)

In [ ]:
np.mean([1,2,3])

In [ ]:

np.mean([1,2,3],out=array)

In [ ]:

np.mean([1,2,3],axis=1)

In [ ]:
result=np.empty(2)
np.mean([[1,2,3],
        [4,5,6]],keepdims=True)

In [ ]:
result = np.mean([1,2,3])

In [ ]:
result


In [ ]:
np.empty([2,3])

In [ ]:
np.empty([1,2,3])

In [ ]:
np.zeros([1,2,3])

In [ ]:
np.empty([2,3],like=[[2,2,2,]])

In [ ]:
import numpy as np


In [ ]:
result=np.array([1,2,3],dtype=int)

In [ ]:
np.array(result,dtype=float)

In [ ]:
l=[[[0,1]]*10]*3  # --> a way to create list.

In [ ]:
l

In [ ]:
from sys import getsizeof
import numpy as np
my_list = [1, 2, 3, 4, 5]
n=np.array(my_list)
size = getsizeof(my_list)
print(size)  # Prints the size of my_list in bytes
print(n.size*n.itemsize)

In [ ]:
x1=np.array([1,2,3,4])
x2=np.array([5,6,6,4])

x1+x2

In [ ]:
x1 = np.arange(9.0).reshape((2,7))

In [ ]:
x1

In [ ]:
import numpy as np
np.zeros(4)

In [ ]:
np.nan

In [ ]:
0*np.nan

In [ ]:
1+np.nan

In [ ]:
np.nan/5

In [ ]:
np.nan% 4

In [ ]:
import re
a = re.search('a','Python Quiz')
print(a)

In [4]:
import numpy as np
np.tile([1],(1,5))

array([[1, 1, 1, 1, 1]])

In [1]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

w1, w2, w3 = 0.3, 0.2, 0.5
weights = [w1, w2, w3]

In [2]:
def yeild(region,weights):
    result=0
    for x,w in zip(region,weights):
        result+=x*w
    return result

In [3]:
yeild(kanto,weights)

56.8

In [1]:
import numpy as np

In [6]:
np.__cached__

'C:\\ProgramData\\anaconda3\\lib\\site-packages\\numpy\\__pycache__\\__init__.cpython-310.pyc'

In [11]:
(np.show_config())

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Lib

TypeError: 'NoneType' object is not iterable

In [16]:
np.arange(3)

array([0, 1, 2])

In [17]:
np.arange(9).reshape((3,3)) + np.arange(3).reshape(3,1)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [37]:
zeros = np.zeros((2,8),int)

In [46]:
zeros.reshape(4,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
arr1 = np.array([1,3])

In [40]:
arr1

array([1, 3])

In [41]:
arr2 = np.array([9,6])

In [42]:
arr2

array([9, 6])

In [43]:
arr1 + arr2

array([10,  9])

In [45]:
np.concatenate((arr1,arr2))

array([1, 3, 9, 6])

In [47]:
arr1 = np.tile([0,1],4)

In [48]:
arr2 = np.tile([1,0],4)

In [49]:
arr1 

array([0, 1, 0, 1, 0, 1, 0, 1])

In [50]:
arr2

array([1, 0, 1, 0, 1, 0, 1, 0])

In [52]:
arr3 = np.concatenate((arr1,arr2))

In [53]:
arr3

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0])

In [60]:
arr4 = np.tile(arr3,4).reshape(8,8)

In [59]:
matrix=np.zeros((8,8),int)
matrix[1::2,0::2]=1 #---> to put 1 on col =1 to col = last
matrix[::2,1::2]=1   # ---> to put 1 on col=0 to col=last-1
print(matrix)

# 1 represents black and 0 represents white

# list[start:stop:step] or np.array[start:stop:step]
# so "::2" means start=0 and stop=0 and step=2=every other element

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [61]:
matrix == arr4

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [62]:
arr4.shape

(8, 8)

In [63]:
# https://www.freetext.org/Introduction_to_Linear_Algebra/Basic_Vector_Operations/Normalization/

# go here to understand matrix normalization 